spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      routes:
        - id: demo-resource-service
          uri: lb://demo-resource-service
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
#      routes:
#        - id: authentification-service
#          uri: lb://AUTHENTICATION-SERVICE
#          predicates:
#            - Path=/uaa/**
#        - id: demo-resource-service
#          uri: lb://DEMO-RESOURCE-SERVICE
#          predicates:
#            - Path=/demo/**
server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
