eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: demo-resource-service
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9098/oauth/token_key

logging.level.org.springframework.security: DEBUG
